lzc-sdk-version: "0.1"
name: warpgate
min_os_version: 1.3.8
package: cloud.lazycat.app.warpgate
version: 0.14.1
description: 无需配置的ssh\http\pg和mysql堡垒机服务
homepage: https://github.com/warp-tech/warpgate
author: warp-tech
application:
    subdomain: warpgate
    background_task: true
    public_path:
        - /
    ingress:
        - protocol: tcp
          port: 8888
          service: warpgate
          send_port_info: true
          yes_i_want_80_443: true

        - protocol: tcp
          port: 2222
          service: warpgate

        - protocol: tcp
          port: 33306
          service: warpgate
services:
    warpgate:
        image: registry.lazycat.cloud/czyt/warp-tech/warpgate:0b9a6f0ea7f2fba1
        binds:
            - /lzcapp/var/data:/data
        environment:
            - WARPGATE_ADMIN_PASSWORD={{.U.adminpassword }}

        setup_script: |
            if [ -f /lzcapp/var/data/warpgate.yaml ]; then
              echo "warpgate.yaml already exists"
            else
              echo "warpgate.yaml does not exist, creating it"
              /usr/local/bin/warpgate unattended-setup --data-path /data --http-port 8888 --ssh-port 2222 --mysql-port 33306  && cp /etc/warpgate.yaml /data/warpgate.yaml
            fi
